### ISSUE TITLE
Converting twig before mjml

### ISSUE THREAD

**Issue by fogx** [assoconnect/mjml-bundle#7]
Hi,
i am trying to use your plugin to compile my twig & mjml email templates.
However, i am running into the following issue:
It seems as though the mjml-bundle runs the mjml compilation before the twig compilation. [this](https://github.com/mjmlio/mjml/issues/459#issuecomment-264876713) and [this](https://github.com/mjmlio/mjml/issues/457) user state, that twig should probably be run before mjml to get the proper html output. Is there a way to achieve this with this plugin?

**Comment by sylfabre** [comment]
@fogx Hello,

When we wrote this plugin, compiling MJML was not so speedy (https://github.com/mjmlio/mjml/issues/457#issuecomment-267292110) and that was an issue for us for transactional emails.

It looks like with version 4 compiling MJML is now faster so I guess we could do now twig => mjml => html

Is the current process causing an issue to you?

**Comment by fogx** [comment]
thanks for the speedy answer @sylfabre 
I am running into issues when using twig variables inside the mjml code, like this:
`<mj-body background-color="{{ color_background }}">`
since the variable will not be injected properly during mjml compilation.

This also causes problems when using conditional twig statements, because mjml will try to build html from sections that won't be included in the final code.

**Comment by sylfabre** [comment]
@fogx ok I understand. This is a valid use case that is currently not handled.
Sadly, right now I don't have any workaround for you :/

**Comment by fogx** [comment]
damn :( probably no ETA for a change either?

**Comment by sylfabre** [comment]
@fogx sadly no ETA
